@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR
skinparam classAttributeFontColor white
skinparam linetype ortho

Package Model as ModelPackage <<Rectangle>>{
Class "<<interface>>\nReadOnlyAddressBook" as ReadOnlyAddressBook
Class "<<interface>>\nReadOnlyUserPrefs" as ReadOnlyUserPrefs
Class "<<interface>>\nModel" as Model

Class AddressBook
Class ModelManager
Class UserPrefs

Class UniquePersonList
Class Person
Class PropertyPreference

Class UniqueTagMap
Class Tag

Class UniqueListingList
Class Listing
Class PriceRange

Class SearchContext
Class "<<enumerations>>\nSearchType" as SearchType {
    PERSON
    LISTING
    NONE
}

Class A #FFFFFF
Class B #FFFFFF
Class C #FFFFFF
}

Class HiddenOutside #FFFFFF
Class DOutside #FFFFFF
Class EOutside #FFFFFF

HiddenOutside ..> Model

' Core interfaces
AddressBook .up.|> ReadOnlyAddressBook
ModelManager .up.|> Model
Model .right.> ReadOnlyUserPrefs
Model .left.> ReadOnlyAddressBook
ModelManager -left-> "1" AddressBook
ModelManager -right-> "1" UserPrefs
UserPrefs .up.|> ReadOnlyUserPrefs

' Unique Lists
AddressBook *--> "1" UniquePersonList
AddressBook *--> "1" UniqueListingList
AddressBook *--> "1" UniqueTagMap

' Person
UniquePersonList --> "~* all" Person
Person "1" *-right-> "*" PropertyPreference
PropertyPreference "*" -right-> "1" Person

' Listing
UniqueListingList ---> "all ~* " Listing

' Tag
UniqueTagMap ----> "all ~* " Tag

' Associations
Listing "~*" <-> "specification ~* " Tag
Tag "~* criteria" <-up-> "~*" PropertyPreference
Person "owner ~*" <-left-> "~*" Listing
Listing "1" -down-> "1" PriceRange
PropertyPreference "1" -right-> "1" PriceRange

' Misc
SearchContext *-> "1" SearchType

' Filtering
ModelManager ------> "filtered ~* " Tag
ModelManager --> "filtered ~*" Person
ModelManager --> "filtered ~*" Listing
ModelManager *-> "1" SearchContext

' Hidden associations for formatting and tidiness
UniqueTagMap -[hidden]right-> UniquePersonList
B -[hidden]up-> ModelManager
UniquePersonList -[hidden]up--> EOutside
UniqueTagMap -[hidden]up-> DOutside
UniqueListingList -[hidden]up->AddressBook
UniquePersonList -[hidden]left-> ModelManager
UniqueTagMap -[hidden]up-> ModelManager
Person -[hidden]up--> A
C -[hidden]up-> Listing
PriceRange -[hidden]left->C
SearchContext -[hidden]down->UserPrefs

@enduml
